import book1 from "../../assets/Canopy/A handbook on First Aid.jpg";
import book2 from "../../assets/Canopy/a helpful guide to healthy living.jpg";
import book3 from "../../assets/Canopy/a letter to my Doctor.jpg";
import book4 from "../../assets/Canopy/A letter to my Patient.jpg";
import book5 from "../../assets/Canopy/essay on public management.jpg";
import book6 from "../../assets/Canopy/Higher civil servants and their political master.jpg";
import book7 from "../../assets/Canopy/history of imosan.jpg";
import book8 from "../../assets/Canopy/Ideas for Development.jpg";
import book9 from "../../assets/Canopy/Law of Happy Life.jpg";
import book10 from "../../assets/Canopy/nigeria and i.jpg";
import book11 from "../../assets/Canopy/nigeria Governance and development.jpg";
import book12 from "../../assets/Canopy/Ogunfowodu Royal Family History.jpg";
import book13 from "../../assets/Canopy/Road Traffic Accidents.jpg";
import book14 from "../../assets/Canopy/Selected Speeches Memoranda and Articles of Alhaji Kehinde Ayinde Ogunfowodu.jpg";
import book15 from "../../assets/Canopy/Sheikh Abubakar Gumi.jpg";
import book16 from "../../assets/Canopy/The Diary of a Muslim Pilgrim.jpg";
import book17 from "../../assets/Canopy/The Integrity of the Bar.jpg";
import book18 from "../../assets/Canopy/Whither Nigeria.jpg";
import book19 from "../../assets/Canopy/reflection.png";

export const discoveryData = [
  {
    id: 19,
    image: book19,
    title: "Reflections on Government and Development in Nigerian",
    publisher: "Brandon & Partners",
    yearOfPublishing: 2017,
    numberOfPages: 300,
    isbn: "978-3-16-148410-0",
    format: "Paperback",
    author: "Ladipo Ademolekun",
    categories: ["Health, Emergency Care"],
    price: "3000",
    genre: "Educational",
    language: "English",
    description:
      "A comprehensive guide to handling medical emergencies effectively.",
  },
  {
    id: 1,
    image: book1,
    title: "A Handbook on First Aid",
    publisher: "Brandon & Partners",
    yearOfPublishing: 2017,
    numberOfPages: 300,
    isbn: "978-3-16-148410-0",
    format: "Paperback",
    author: "Umar Faruk Adamu",
    categories: ["Health, Emergency Care"],
    price: "3299",
    genre: "Educational",
    language: "English",
    description:
      "A comprehensive guide to handling medical emergencies effectively.",
  },
  {
    id: 2,
    image: book2,
    title: "An helpful guide to healthy living",
    publisher: "Serenity Press",
    yearOfPublishing: 2021,
    numberOfPages: 250,
    isbn: "978-1-23-456789-0",
    format: "Hardcover",
    author: "Umar Faruk Adamu",
    categories: ["Self-Help, Well-being"],
    price: "4999",
    genre: "Motivational",
    language: "English",
    description: "A journey into mindfulness and stress management techniques.",
  },
  {
    id: 3,
    image: book3,
    title: "A letter to my Doctor",
    publisher: "BlueWave Books",
    yearOfPublishing: 2019,
    numberOfPages: 320,
    isbn: "978-3-19-159872-1",
    format: "eBook",
    author: "Umar Faruk Adamu",
    categories: ["Science, Nature"],
    price: "2799",
    genre: "Educational",
    language: "English",
    description: "Exploring the unknown depths of our oceans and marine life.",
  },
  {
    id: 4,
    image: book4,
    title: "A letter to my Patient",
    publisher: "Tech Horizon",
    yearOfPublishing: 2022,
    numberOfPages: 400,
    isbn: "978-3-16-987654-3",
    format: "Paperback",
    author: "Umar Faruk Adamu",
    categories: ["Technology, Science"],
    price: "5499",
    genre: "Non-Fiction",
    language: "English",
    description:
      "A deep dive into artificial intelligence and its impact on society.",
  },
  {
    id: 5,
    image: book5,
    title: "Essay on public management",
    publisher: "Legacy Publishing",
    yearOfPublishing: 2016,
    numberOfPages: 280,
    isbn: "978-3-11-987654-3",
    format: "Paperback",
    author: "Ladipo Ademolekun",
    categories: ["History, Mythology"],
    price: "3199",
    genre: "Historical Fiction",
    language: "English",
    description: "A collection of intriguing tales from ancient civilizations.",
  },
  {
    id: 6,
    image: book6,
    title: "Higher civil servants and their political master",
    publisher: "MindWell Books",
    yearOfPublishing: 2020,
    numberOfPages: 310,
    isbn: "978-3-22-876543-1",
    format: "Hardcover",
    author: "Ladipo Ademolekun",
    categories: ["Psychology, Self-Help"],
    price: "4599",
    genre: "Self-Help",
    language: "English",
    description:
      "Understanding the psychology behind true happiness and well-being.",
  },
  {
    id: 7,
    image: book7,
    title: "History of imosan",
    publisher: "Epic Reads",
    yearOfPublishing: 2018,
    numberOfPages: 370,
    isbn: "978-3-11-112233-4",
    format: "Paperback",
    author: "Kehinde Ayinde Ogunfowodu",
    categories: ["Adventure, Fiction"],
    price: "3899",
    genre: "Novel",
    language: "English",
    description:
      "A thrilling journey across uncharted lands and hidden treasures.",
  },
  {
    id: 8,
    image: book8,
    title: "Ideas for Development",
    publisher: "Fantasy World",
    yearOfPublishing: 2015,
    numberOfPages: 290,
    isbn: "978-3-45-123987-6",
    format: "Hardcover",
    author: "Ladipo Ademolekun",
    categories: ["Fantasy, Folklore"],
    price: "4299",
    genre: "Mythology",
    language: "English",
    description:
      "A captivating collection of legendary stories from different cultures.",
  },
  {
    id: 9,
    image: book9,
    title: "Law of Happy Life",
    publisher: "Galactic Press",
    yearOfPublishing: 2021,
    numberOfPages: 280,
    isbn: "978-3-45-456789-0",
    format: "eBook",
    author: "A.A Sanda",
    categories: ["Science, Astronomy"],
    price: "3999",
    genre: "Educational",
    language: "English",
    description:
      "A fascinating look at the stars, planets, and galaxies beyond.",
  },
  {
    id: 10,
    image: book10,
    title: "Nigeria And I",
    publisher: "Gourmet Reads",
    yearOfPublishing: 2023,
    numberOfPages: 350,
    isbn: "978-3-45-789012-3",
    format: "Paperback",
    author: "Ladipo Ademolekun",
    categories: ["Cooking, Recipe Books"],
    price: "1500",
    genre: "Culinary",
    language: "English",
    description: "A complete guide to mastering global cuisines.",
  },
  {
    id: 11,
    image: book11,
    title: "Nigeria Governance and development",
    publisher: "Inspire Publishing",
    yearOfPublishing: 2020,
    numberOfPages: 320,
    isbn: "978-3-45-987654-0",
    format: "Hardcover",
    author: "Ladipo Ademolekun",
    categories: ["Philosophy, Personal Development"],
    price: "3999",
    genre: "Self-Improvement",
    language: "English",
    description: "A deep exploration of self-awareness and inner peace.",
  },
  {
    id: 12,
    image: book12,
    title: "Ogunfowodu Royal Family History",
    publisher: "Corporate Mind",
    yearOfPublishing: 2021,
    numberOfPages: 340,
    isbn: "978-3-45-321098-7",
    format: "eBook",
    author: "Alh. K.A. Ogunfowodu",
    categories: ["Business, Economics"],
    price: "5999",
    genre: "Business",
    language: "English",
    description:
      "A guide to mastering business strategies and achieving success.",
  },
  {
    id: 13,
    image: book13,
    title: "Road Traffic Accidents",
    publisher: "Creative Minds",
    yearOfPublishing: 2022,
    numberOfPages: 300,
    isbn: "978-3-45-765432-1",
    format: "Hardcover",
    author: "Umar Faruk Adamu",
    categories: ["Writing, Fiction"],
    price: "4499",
    genre: "Literature",
    language: "English",
    description:
      "A comprehensive guide to writing stories and novels from scratch.",
  },
  {
    id: 14,
    image: book14,
    title:
      "Selected Speeches Memoranda and Articles of Alhaji Kehinde Ayinde Ogunfowodu",
    publisher: "Happiness House",
    yearOfPublishing: 2019,
    numberOfPages: 320,
    isbn: "978-3-45-321098-7",
    format: "Hardcover",
    author: "Alh. K.A. Ogunfowodu",
    categories: ["Psychology, Self-Help"],
    price: "4999",
    genre: "Self-Help",
    language: "English",
    description:
      "A comprehensive guide to cultivating happiness and well-being.",
  },
  {
    id: 15,
    image: book15,
    title: "Sheikh Abubakar Gumi",
    publisher: "Happiness House",
    yearOfPublishing: 2019,
    numberOfPages: 320,
    isbn: "978-3-45-321098-7",
    format: "Hardcover",
    author: "Alh. K.A. Ogunfowodu",
    categories: ["Psychology, Self-Help"],
    price: "4999",
    genre: "Self-Help",
    language: "English",
    description:
      "A comprehensive guide to cultivating happiness and well-being.",
  },
  {
    id: 16,
    image: book16,
    title: "The Diary of a Muslim Pilgrim",
    publisher: "Happiness House",
    yearOfPublishing: 2019,
    numberOfPages: 320,
    isbn: "978-3-45-321098-7",
    format: "Hardcover",
    author: "Umar Faruk Adamu",
    categories: ["Psychology, Self-Help"],
    price: "4999",
    genre: "Self-Help",
    language: "English",
    description:
      "A comprehensive guide to cultivating happiness and well-being.",
  },
  {
    id: 17,
    image: book17,
    title: "The Integrity of the Bar",
    publisher: "Happiness House",
    yearOfPublishing: 2019,
    numberOfPages: 320,
    isbn: "978-3-45-321098-7",
    format: "Hardcover",
    author: "A. A. Sanda",
    categories: ["Psychology, Self-Help"],
    price: "4999",
    genre: "Self-Help",
    language: "English",
    description:
      "A comprehensive guide to cultivating happiness and well-being.",
  },
  {
    id: 18,
    image: book18,
    title: "Whither Nigeria",
    publisher: "Happiness House",
    yearOfPublishing: 2019,
    numberOfPages: 320,
    isbn: "978-3-45-321098-7",
    format: "Hardcover",
    author: "Lapipo Ademolekun & Adele Jinadu",
    categories: ["Psychology, Self-Help"],
    price: "4999",
    genre: "Self-Help",
    language: "English",
    description:
      "A comprehensive guide to cultivating happiness and well-being.",
  },
];
